local _, addon = ...

local translations = {
    ["deDE"] = {
        OPEN_ADDON = "Better Patch Notes öffnen",
        HIDE_MINIMAP_BUTTON = "Minikarten-Schaltfläche ausblenden",
        TITLE = "Bessere Patchnotes",
        LIVE = "Live",
        PTR = "PTR",
        CLASS_CHANGES = "Klassenänderungen",
        CLASS_WIDE = "Klassenweit",
        OTHER_SPECIALIZATIONS = "Andere Spezialisierungen",
        DUNGEON_CHANGES = "Dungeon-Änderungen",
        RAID_CHANGES = "Schlachtzugsänderungen",
        NO_CHANGES = "Keine relevanten Änderungen.",
        ENGLISH_FALLBACK = "Englischer Originaltext",
        CLOSE = "Schließen",
        NEW = "Neu",
        SOURCE = "Quelle",
        COPY_SOURCE_INSTRUCTION =
            "Drücke Strg+C, um diesen Quellenlink zu kopieren.",
    },
    ["en"] = {
        OPEN_ADDON = "Open Better Patch Notes",
        HIDE_MINIMAP_BUTTON = "Hide minimap button",
        TITLE = "Better Patch Notes",
        LIVE = "Live",
        PTR = "PTR",
        CLASS_CHANGES = "Class changes",
        CLASS_WIDE = "Class-wide",
        OTHER_SPECIALIZATIONS = "Other specializations",
        DUNGEON_CHANGES = "Dungeon changes",
        RAID_CHANGES = "Raid changes",
        NO_CHANGES = "No relevant changes.",
        ENGLISH_FALLBACK = "English source text",
        CLOSE = "Close",
        NEW = "New",
        SOURCE = "Source",
        COPY_SOURCE_INSTRUCTION =
            "Press Ctrl+C to copy this source link.",
    },
    ["esES"] = {
        OPEN_ADDON = "Abrir Better Patch Notes",
        HIDE_MINIMAP_BUTTON = "Ocultar botón del minimapa",
        TITLE = "Mejores notas del parche",
        LIVE = "En vivo",
        PTR = "RPP",
        CLASS_CHANGES = "Cambios de clase",
        CLASS_WIDE = "Toda la clase",
        OTHER_SPECIALIZATIONS = "Otras especializaciones",
        DUNGEON_CHANGES = "Cambios de mazmorras",
        RAID_CHANGES = "Cambios de bandas",
        NO_CHANGES = "No hay cambios relevantes.",
        ENGLISH_FALLBACK = "Texto original en inglés",
        CLOSE = "Cerrar",
        NEW = "Nuevo",
        SOURCE = "Fuente",
        COPY_SOURCE_INSTRUCTION =
            "Pulsa Ctrl+C para copiar este enlace de origen.",
    },
    ["esMX"] = {
        OPEN_ADDON = "Abrir Better Patch Notes",
        HIDE_MINIMAP_BUTTON = "Ocultar botón del minimapa",
        TITLE = "Mejores notas del parche",
        LIVE = "En vivo",
        PTR = "RPP",
        CLASS_CHANGES = "Cambios de clase",
        CLASS_WIDE = "Toda la clase",
        OTHER_SPECIALIZATIONS = "Otras especializaciones",
        DUNGEON_CHANGES = "Cambios de calabozos",
        RAID_CHANGES = "Cambios de bandas",
        NO_CHANGES = "No hay cambios relevantes.",
        ENGLISH_FALLBACK = "Texto original en inglés",
        CLOSE = "Cerrar",
        NEW = "Nuevo",
        SOURCE = "Fuente",
        COPY_SOURCE_INSTRUCTION =
            "Presiona Ctrl+C para copiar este enlace de origen.",
    },
    ["frFR"] = {
        OPEN_ADDON = "Ouvrir Better Patch Notes",
        HIDE_MINIMAP_BUTTON = "Masquer le bouton de la minicarte",
        TITLE = "Meilleures notes de mise à jour",
        LIVE = "En jeu",
        PTR = "RPT",
        CLASS_CHANGES = "Modifications de classe",
        CLASS_WIDE = "Toute la classe",
        OTHER_SPECIALIZATIONS = "Autres spécialisations",
        DUNGEON_CHANGES = "Modifications des donjons",
        RAID_CHANGES = "Modifications des raids",
        NO_CHANGES = "Aucune modification pertinente.",
        ENGLISH_FALLBACK = "Texte source anglais",
        CLOSE = "Fermer",
        NEW = "Nouveau",
        SOURCE = "Source",
        COPY_SOURCE_INSTRUCTION =
            "Appuyez sur Ctrl+C pour copier ce lien source.",
    },
    ["itIT"] = {
        OPEN_ADDON = "Apri Better Patch Notes",
        HIDE_MINIMAP_BUTTON = "Nascondi il pulsante della minimappa",
        TITLE = "Note della patch migliorate",
        LIVE = "Live",
        PTR = "RPP",
        CLASS_CHANGES = "Modifiche alla classe",
        CLASS_WIDE = "Intera classe",
        OTHER_SPECIALIZATIONS = "Altre specializzazioni",
        DUNGEON_CHANGES = "Modifiche alle spedizioni",
        RAID_CHANGES = "Modifiche alle incursioni",
        NO_CHANGES = "Nessuna modifica pertinente.",
        ENGLISH_FALLBACK = "Testo originale inglese",
        CLOSE = "Chiudi",
        NEW = "Novità",
        SOURCE = "Fonte",
        COPY_SOURCE_INSTRUCTION =
            "Premi Ctrl+C per copiare questo link alla fonte.",
    },
    ["koKR"] = {
        OPEN_ADDON = "Better Patch Notes 열기",
        HIDE_MINIMAP_BUTTON = "미니맵 버튼 숨기기",
        TITLE = "향상된 패치 노트",
        LIVE = "라이브",
        PTR = "공개 테스트 서버",
        CLASS_CHANGES = "직업 변경 사항",
        CLASS_WIDE = "직업 공통",
        OTHER_SPECIALIZATIONS = "다른 전문화",
        DUNGEON_CHANGES = "던전 변경 사항",
        RAID_CHANGES = "공격대 변경 사항",
        NO_CHANGES = "관련 변경 사항이 없습니다.",
        ENGLISH_FALLBACK = "영문 원문",
        CLOSE = "닫기",
        NEW = "신규",
        SOURCE = "출처",
        COPY_SOURCE_INSTRUCTION =
            "Ctrl+C를 눌러 출처 링크를 복사하세요.",
    },
    ["ptBR"] = {
        OPEN_ADDON = "Abrir Better Patch Notes",
        HIDE_MINIMAP_BUTTON = "Ocultar botão do minimapa",
        TITLE = "Notas de patch aprimoradas",
        LIVE = "Ao vivo",
        PTR = "RTP",
        CLASS_CHANGES = "Alterações de classe",
        CLASS_WIDE = "Toda a classe",
        OTHER_SPECIALIZATIONS = "Outras especializações",
        DUNGEON_CHANGES = "Alterações de masmorras",
        RAID_CHANGES = "Alterações de raides",
        NO_CHANGES = "Nenhuma alteração relevante.",
        ENGLISH_FALLBACK = "Texto original em inglês",
        CLOSE = "Fechar",
        NEW = "Novo",
        SOURCE = "Fonte",
        COPY_SOURCE_INSTRUCTION =
            "Pressione Ctrl+C para copiar este link da fonte.",
    },
    ["ruRU"] = {
        OPEN_ADDON = "Открыть Better Patch Notes",
        HIDE_MINIMAP_BUTTON = "Скрыть кнопку у мини-карты",
        TITLE = "Улучшенные описания обновлений",
        LIVE = "Основные миры",
        PTR = "PTR",
        CLASS_CHANGES = "Изменения класса",
        CLASS_WIDE = "Для всего класса",
        OTHER_SPECIALIZATIONS = "Другие специализации",
        DUNGEON_CHANGES = "Изменения подземелий",
        RAID_CHANGES = "Изменения рейдов",
        NO_CHANGES = "Подходящих изменений нет.",
        ENGLISH_FALLBACK = "Исходный текст на английском",
        CLOSE = "Закрыть",
        NEW = "Новое",
        SOURCE = "Источник",
        COPY_SOURCE_INSTRUCTION =
            "Нажмите Ctrl+C, чтобы скопировать ссылку на источник.",
    },
    ["zhCN"] = {
        OPEN_ADDON = "打开 Better Patch Notes",
        HIDE_MINIMAP_BUTTON = "隐藏小地图按钮",
        TITLE = "更好的补丁说明",
        LIVE = "正式服",
        PTR = "测试服",
        CLASS_CHANGES = "职业改动",
        CLASS_WIDE = "全职业",
        OTHER_SPECIALIZATIONS = "其他专精",
        DUNGEON_CHANGES = "地下城改动",
        RAID_CHANGES = "团队副本改动",
        NO_CHANGES = "没有相关改动。",
        ENGLISH_FALLBACK = "英文原文",
        CLOSE = "关闭",
        NEW = "新",
        SOURCE = "来源",
        COPY_SOURCE_INSTRUCTION = "按 Ctrl+C 复制来源链接。",
    },
    ["zhTW"] = {
        OPEN_ADDON = "開啟 Better Patch Notes",
        HIDE_MINIMAP_BUTTON = "隱藏小地圖按鈕",
        TITLE = "更好的更新說明",
        LIVE = "正式服",
        PTR = "測試服",
        CLASS_CHANGES = "職業改動",
        CLASS_WIDE = "全職業",
        OTHER_SPECIALIZATIONS = "其他專精",
        DUNGEON_CHANGES = "地城改動",
        RAID_CHANGES = "團隊副本改動",
        NO_CHANGES = "沒有相關改動。",
        ENGLISH_FALLBACK = "英文原文",
        CLOSE = "關閉",
        NEW = "新",
        SOURCE = "來源",
        COPY_SOURCE_INSTRUCTION = "按 Ctrl+C 複製來源連結。",
    },
}

local locale = GetLocale()
if locale == "enUS" or locale == "enGB" then
    locale = "en"
end

local selected = translations[locale] or translations.en

function addon.GetText(key)
    return selected[key] or translations.en[key] or key
end
